version: '2.3'

x-volumes:
  &default-volumes
    # Define all volumes you would like to have real-time mounted into the docker containers
    volumes:
      - .:/null:delegated

services:

  cli: # cli container, will be used for executing composer and any local commands (drush, drupal, etc.)
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.govcms8
    image: ${DOCKERHUB_NAMESPACE:-govcms}/govcms8
    << : *default-volumes # loads the defined volumes from the top
    environment:
      LAGOON_ROUTE: &default-url ${LOCALDEV_URL:-http://govcms8.docker.amazee.io}

  test:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.test
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcms}/govcms8
    << : *default-volumes
    environment:
      LAGOON_ROUTE: *default-url
    depends_on:
      - cli

  nginx:
    build:
      context: .
      dockerfile: .docker/Dockerfile.nginx
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcms}/govcms8
    << : *default-volumes
    environment:
      LAGOON_LOCALDEV_URL: *default-url
    networks:
      - amazeeio-network
      - default

  php:
    build:
      context: .
      dockerfile: .docker/Dockerfile.php
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcms}/govcms8
    << : *default-volumes # loads the defined volumes from the top

  mariadb:
    image: amazeeio/mariadb-drupal
    ports:
      - "3306" # exposes the port 3306 with a random local port, find it with `docker-compose port mariadb 3306`

  redis:
    image: amazeeio/redis

networks:
  amazeeio-network:
    external: true
